//! ZX Spectrum BASIC keyword-to-token mapping.
//!
//! Token values $A5–$FF. Sorted longest-first so the parser
//! performs greedy matching (e.g. "GO TO" before "GO").

use KeywordRole::*;

/// Where a keyword is syntactically valid.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KeywordRole {
    /// Only at statement boundaries (start of line, after `:`, after `THEN`).
    Statement,
    /// Anywhere in expressions: functions, operators, constants.
    Expression,
    /// At statement boundaries AND within PRINT/INPUT item lists.
    PrintItem,
    /// Context-dependent: matched only when the parser expects them
    /// (TO/STEP in FOR, THEN after IF, LINE after SAVE/LOAD).
    SubKeyword,
    /// Symbol operators — always match.
    Symbol,
    /// Rest-of-line: REM (literal) and DATA (no keyword matching in values).
    RestOfLine,
}

/// `(keyword_text, token_byte, role)` — sorted by keyword length descending.
pub const KEYWORDS: &[(&str, u8, KeywordRole)] = &[
    ("RANDOMIZE ", 0xF9, Statement),
    ("CONTINUE ", 0xE8, Statement),
    ("RESTORE ", 0xE5, Statement),
    ("INVERSE ", 0xDD, PrintItem),
    ("BRIGHT ", 0xDC, PrintItem),
    ("VERIFY ", 0xD6, Statement),
    ("CIRCLE ", 0xD8, Statement),
    ("BORDER ", 0xE7, Statement),
    ("RETURN ", 0xFE, Statement),
    ("LPRINT ", 0xE0, Statement),
    ("SCREEN$ ", 0xAA, Expression),
    ("INKEY$ ", 0xA6, Expression),
    ("FORMAT ", 0xD0, Statement),
    ("MERGE ", 0xD5, Statement),
    ("ERASE ", 0xD2, Statement),
    ("CLOSE #", 0xD4, Statement),
    ("OPEN #", 0xD3, Statement),
    ("PRINT ", 0xF5, Statement),
    ("INPUT ", 0xEE, Statement),
    ("PAUSE ", 0xF2, Statement),
    ("CLEAR ", 0xFD, Statement),
    ("FLASH ", 0xDB, PrintItem),
    ("PAPER ", 0xDA, PrintItem),
    ("POINT ", 0xA9, Expression),
    ("LLIST ", 0xE1, Statement),
    ("GO SUB ", 0xED, Statement),
    ("GO TO ", 0xEC, Statement),
    ("DEF FN ", 0xCE, Statement),
    ("DRAW ", 0xFC, Statement),
    ("PLOT ", 0xF6, Statement),
    ("POKE ", 0xF4, Statement),
    ("NEXT ", 0xF3, Statement),
    ("READ ", 0xE3, Statement),
    ("DATA ", 0xE4, RestOfLine),
    ("SAVE ", 0xF8, Statement),
    ("LOAD ", 0xEF, Statement),
    ("LIST ", 0xF0, Statement),
    ("STOP ", 0xE2, Statement),
    ("BEEP ", 0xD7, Statement),
    ("MOVE ", 0xD1, Statement),
    ("COPY", 0xFF, Statement),
    ("OVER ", 0xDE, PrintItem),
    ("ATTR ", 0xAB, Expression),
    ("VAL$ ", 0xAE, Expression),
    ("STR$ ", 0xC1, Expression),
    ("CHR$ ", 0xC2, Expression),
    ("STEP ", 0xCD, SubKeyword),
    ("THEN ", 0xCB, SubKeyword),
    ("LINE ", 0xCA, SubKeyword),
    ("PEEK ", 0xBE, Expression),
    ("CODE ", 0xAF, Expression),
    ("DIM ", 0xE9, Statement),
    ("REM ", 0xEA, RestOfLine),
    ("FOR ", 0xEB, Statement),
    ("RUN ", 0xF7, Statement),
    ("CLS", 0xFB, Statement),
    ("LET ", 0xF1, Statement),
    ("NEW", 0xE6, Statement),
    ("OUT ", 0xDF, Statement),
    ("INK ", 0xD9, PrintItem),
    ("CAT ", 0xCF, Statement),
    ("NOT ", 0xC3, Expression),
    ("BIN ", 0xC4, Expression),
    ("AND ", 0xC6, Expression),
    ("VAL ", 0xB0, Expression),
    ("LEN ", 0xB1, Expression),
    ("SIN ", 0xB2, Expression),
    ("COS ", 0xB3, Expression),
    ("TAN ", 0xB4, Expression),
    ("ASN ", 0xB5, Expression),
    ("ACS ", 0xB6, Expression),
    ("ATN ", 0xB7, Expression),
    ("EXP ", 0xB9, Expression),
    ("INT ", 0xBA, Expression),
    ("SQR ", 0xBB, Expression),
    ("SGN ", 0xBC, Expression),
    ("ABS ", 0xBD, Expression),
    ("USR ", 0xC0, Expression),
    ("IF ", 0xFA, Statement),
    ("OR ", 0xC5, Expression),
    ("AT ", 0xAC, PrintItem),
    ("TO ", 0xCC, SubKeyword),
    ("IN ", 0xBF, Expression),
    ("LN ", 0xB8, Expression),
    ("FN ", 0xA8, Expression),
    ("TAB ", 0xAD, PrintItem),
    ("PI", 0xA7, Expression),
    ("RND", 0xA5, Expression),
];
